name: Daily Expiry Check

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: 

jobs:
  run-api-route:
    runs-on: ubuntu-latest
    
    steps:
      - name: Hit the Check Expiry API Endpoint
        run: |
          curl -X GET "https://alodat-docs.vercel.app/api/cron/check-expiry" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
